"""Collect everything the project report needs into one JSON payload.

The .docx is generated by ``scripts/make_report.js`` from the file this module
writes, so every number, table and code listing in the report comes from the
actual results and the actual source files. Re-running this after a new training
run refreshes the report rather than requiring it to be edited by hand.

Usage
-----
    python -m src.report_data
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

from src.metrics import CLASS_NAMES, load_results

PROJECT_ROOT: Path = Path(__file__).resolve().parents[1]
RESULTS_DIR: Path = PROJECT_ROOT / "results"
OUT_PATH: Path = RESULTS_DIR / "report_data.json"

# Models shown in the main comparison, in presentation order.
MAIN_MODELS: list[str] = [
    "TF-IDF + LogReg",
    "LSTM",
    "Bi-GRU",
    "Bi-LSTM + Attention",
    "DistilBERT (fine-tuned)",
]

# Ablations and experiments reported separately, so the headline table stays
# comparable across the five required architectures.
EXPERIMENTS: list[tuple[str, str, str]] = [
    ("Bi-GRU (v2)", "Bi-GRU",
     "2 layers, hidden 192, max_len 320 - capacity experiment"),
    ("Bi-GRU (ord)", "Bi-GRU",
     "ordinal (distance-aware) loss, smoothing 0.15"),
    ("Bi-LSTM + Attention (ord)", "Bi-LSTM + Attention",
     "ordinal (distance-aware) loss, smoothing 0.15"),
]

# Source excerpts: (file, [top-level names to include]).
CODE_SECTIONS: list[dict] = [
    {
        "title": "4.1 DATA PIPELINE - STREAMING, LABELLING AND SPLITTING",
        "file": "src/data.py",
        "names": ["normalise_text", "clean_for_neural", "rating_to_label",
                  "stream_reviews", "stratified_split"],
    },
    {
        "title": "4.2 VOCABULARY, TOKENISATION AND GloVe EMBEDDINGS",
        "file": "src/vocab.py",
        "names": ["tokenize", "build_embedding_matrix"],
    },
    {
        "title": "4.3 MODEL ARCHITECTURE - Bi-LSTM WITH ATTENTION",
        "file": "src/models.py",
        "names": ["AdditiveAttention", "BiLSTMAttentionClassifier"],
    },
    {
        "title": "4.4 TRAINING LOOP - CLASS WEIGHTS, EARLY STOPPING, MIXED PRECISION",
        "file": "src/train.py",
        "names": ["collate", "TrainConfig", "train_model"],
    },
    {
        "title": "4.5 BASELINE - TF-IDF + LOGISTIC REGRESSION",
        "file": "src/baseline.py",
        "names": ["build_pipeline"],
    },
    {
        "title": "4.6 INFERENCE AND THE STREAMLIT WEB APPLICATION",
        "file": "src/predict.py",
        "names": ["SentimentPredictor"],
    },
]

FIGURES: dict[str, str] = {
    "block_diagram": "00_block_diagram.png",
    "class_distribution": "01_class_distribution.png",
    "rating_distribution": "02_rating_distribution.png",
    "review_length": "03_review_length.png",
    "top_words": "04_top_words_per_class.png",
    "model_comparison": "06_model_comparison.png",
    "per_class_f1": "07_per_class_f1.png",
    "confusion_main": "08_confusion_matrix_main.png",
    "attention": "09_attention_heatmaps.png",
    "app_mixed": "10_app_mixed_review.png",
    "app_negative": "11_app_negative_review.png",
}


def extract_source(rel_path: str, names: list[str]) -> str:
    """Return the source of the named top-level definitions, in file order."""
    path = PROJECT_ROOT / rel_path
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    lines = source.splitlines()

    chunks: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef,
                                 ast.ClassDef)):
            continue
        if node.name not in names:
            continue
        start = min([node.lineno] + [d.lineno for d in node.decorator_list]) - 1
        chunks.append("\n".join(lines[start:node.end_lineno]))
    return "\n\n".join(chunks)


def test_case_outputs() -> list[dict]:
    """Run the deployed model on three representative reviews.

    These are the numbers printed in the report's test-case section, generated
    here rather than transcribed, so they cannot drift from the model.
    """
    from src.predict import SentimentPredictor

    cases = [
        {
            "title": "TEST CASE 1 - CLEAR NEGATIVE REVIEW",
            "description": (
                "The customer describes an outright product failure with no "
                "redeeming comment. The model should identify the negative "
                "sentiment with high confidence and attend to the explicit "
                "failure words rather than to neutral product nouns."
            ),
            "text": "Battery died after two weeks and support never replied. "
                    "Complete waste of money.",
        },
        {
            "title": "TEST CASE 2 - CLEAR POSITIVE REVIEW",
            "description": (
                "The customer reports that the product met expectations "
                "exactly. The model should return positive with high "
                "confidence, weighting the satisfaction terms."
            ),
            "text": "Works exactly as described, sound quality is excellent "
                    "and setup took two minutes.",
        },
        {
            "title": "TEST CASE 3 - MIXED REVIEW (CONTRAST DETECTION)",
            "description": (
                "The review contains genuine praise followed by a genuine "
                "complaint, joined by a contrastive conjunction. This is the "
                "case a bag-of-words model cannot resolve, because the "
                "sentiment depends on the structure of the sentence rather "
                "than on which words appear in it. The attention layer is "
                "expected to weight the pivot word most heavily and the model "
                "to return neutral."
            ),
            "text": "The picture quality is genuinely sharp and setup took "
                    "five minutes, but the remote feels cheap and the menus "
                    "are painfully slow.",
        },
    ]

    predictor = SentimentPredictor("bilstm_attention")
    for case in cases:
        pred = predictor.predict(case["text"])
        case["predicted"] = pred.label_name
        case["confidence"] = round(pred.confidence, 4)
        case["probabilities"] = {k: round(v, 4)
                                 for k, v in pred.probabilities.items()}
        case["top_tokens"] = [[t, round(w, 3)] for t, w in pred.top_tokens(6)]
    return cases


def build_payload() -> dict:
    results = load_results()

    def row(name: str) -> dict | None:
        entry = results.get(name)
        if not entry or "test" not in entry:
            return None
        m = entry["test"]
        return {
            "model": name,
            "accuracy": round(m["accuracy"], 4),
            "macro_f1": round(m["macro_f1"], 4),
            "weighted_f1": round(m["weighted_f1"], 4),
            "per_class": {
                c: {k: round(v, 4) if isinstance(v, float) else v
                    for k, v in m["per_class"][c].items()}
                for c in CLASS_NAMES
            },
            "confusion_matrix": m["confusion_matrix"],
            "parameters": entry.get("meta", {}).get("parameters"),
        }

    comparison = [r for r in (row(n) for n in MAIN_MODELS) if r]

    experiments = []
    for name, baseline, note in EXPERIMENTS:
        r = row(name)
        if not r:
            continue
        base = row(baseline)
        r["note"] = note
        r["baseline"] = baseline
        r["baseline_macro_f1"] = base["macro_f1"] if base else None
        r["delta"] = (round(r["macro_f1"] - base["macro_f1"], 4)
                      if base else None)
        experiments.append(r)

    optimisation = []
    opt_path = RESULTS_DIR / "optimization.json"
    if opt_path.exists():
        optimisation = json.loads(opt_path.read_text(encoding="utf-8"))

    distribution = {}
    dist_path = RESULTS_DIR / "class_distribution.json"
    if dist_path.exists():
        distribution = json.loads(dist_path.read_text(encoding="utf-8"))

    misclassified = []
    mis_path = RESULTS_DIR / "misclassified_neutrals.json"
    if mis_path.exists():
        misclassified = json.loads(mis_path.read_text(encoding="utf-8"))

    code = []
    for section in CODE_SECTIONS:
        code.append({
            "title": section["title"],
            "file": section["file"],
            "source": extract_source(section["file"], section["names"]),
        })

    figures = {
        key: str((RESULTS_DIR / "figures" / name).resolve())
        for key, name in FIGURES.items()
        if (RESULTS_DIR / "figures" / name).exists()
    }

    return {
        "comparison": comparison,
        "experiments": experiments,
        "optimisation": optimisation,
        "distribution": distribution,
        "misclassified_neutrals": misclassified[:20],
        "code": code,
        "figures": figures,
        "test_cases": test_case_outputs(),
    }


def main() -> int:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    OUT_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"models in comparison : {len(payload['comparison'])}")
    print(f"experiments          : {len(payload['experiments'])}")
    print(f"optimisation rows    : {len(payload['optimisation'])}")
    print(f"code sections        : {len(payload['code'])}")
    print(f"figures              : {len(payload['figures'])}")
    print(f"saved -> results/report_data.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
